<script setup lang="ts">
import StockChart from "./StockChart.vue";

import * as Data_service from "../data/Data_service";
import * as Data_transformers from "../data/Data_transformers";
import * as Server_data from "../data/Server_data";

const properties = defineProps<{
    symbol: string;
    api_key: string;
}>();

const all_data: Server_data.All_symbol_data = await Data_service.get_all_symbol_data(properties.symbol, properties.api_key, localStorage, false);

const currency = all_data.overview.currency;

const price_chart_data = Data_transformers.create_price_chart(all_data.time_series.entries, currency);
const total_revenue_chart_data = Data_transformers.create_total_revenue_chart(all_data.income_statements.annual_reports, currency);
const net_income_chart_data = Data_transformers.create_net_income_chart(all_data.income_statements.annual_reports, currency);
const earnings_per_share_data = Data_transformers.create_earnings_per_share_chart(all_data.income_statements.annual_reports, all_data.balance_sheets.annual_reports, currency);
const profit_margin_data = Data_transformers.create_profit_margin_chart(all_data.income_statements.annual_reports);
const cash_flow_data = Data_transformers.create_cash_flow_chart(all_data.income_statements.annual_reports, currency);
const debt_levels_data = Data_transformers.create_debt_levels_chart(all_data.income_statements.annual_reports, currency);
const return_on_equity_data = Data_transformers.create_return_on_equity_chart(all_data.income_statements.annual_reports, currency);
const dividend_chart_data = Data_transformers.create_dividend_chart(all_data.time_series.entries, currency);
const dividend_yield_data = Data_transformers.create_dividend_yield_chart(all_data.time_series.entries);
const book_value_per_share_data = Data_transformers.create_book_value_per_share_chart(all_data.income_statements.annual_reports, currency);
const price_to_earnings_ratio_data = Data_transformers.create_price_to_earnings_ratio_chart(all_data.income_statements.annual_reports, currency);

</script>

<template>
    <div>
        <StockChart :chart_data="price_chart_data" type="line"
            description="The stock price represents the market's valuation of the company at a given point in time, and it is influenced by various factors, including the company's financial performance, growth prospects, industry conditions, market sentiment, and overall economic conditions.">
        </StockChart>
        <StockChart :chart_data="total_revenue_chart_data" type="bar"
            description="This represents the total income generated by the company from its core business operations. Steady or growing revenue over time is a positive sign.">
        </StockChart>
        <StockChart :chart_data="net_income_chart_data" type="bar"
            description="Net income is the bottom-line profit after all expenses, taxes, and interest have been accounted for. Positive and growing net income is a good indicator of a healthy company.">
        </StockChart>
        <StockChart :chart_data="earnings_per_share_data" type="bar"
            description="EPS is calculated by dividing the net income by the number of outstanding shares. It shows how much profit the company generates per share and is an important measure for investors.">
        </StockChart>
        <StockChart :chart_data="profit_margin_data" type="bar"
            description="This is the ratio of net income to revenue and indicates the company's ability to generate profit from its sales. A higher profit margin generally indicates better profitability. Profit Margin = (Net Income / Total Revenue) x 100.">
        </StockChart>
        <StockChart :chart_data="cash_flow_data" type="bar"
            description="Look at the company's operating cash flow, investing cash flow, and financing cash flow. Positive and growing operating cash flow is crucial as it reflects the company's ability to generate cash from its core operations.">
        </StockChart>
        <StockChart :chart_data="debt_levels_data" type="bar"
            description="Check the company's total debt and debt-to-equity ratio. High levels of debt can indicate higher financial risk, so it's important to see if the company can manage its debt.">
        </StockChart>
        <StockChart :chart_data="return_on_equity_data" type="bar"
            description="ROE measures the company's ability to generate returns for its shareholders. Higher ROE is generally preferred.">
        </StockChart>
        <StockChart :chart_data="dividend_chart_data" type="bar" description="A consistent or increasing dividend history is generally viewed positively, as it indicates a company's ability
            and willingness to share profits with shareholders.">
        </StockChart>
        <StockChart :chart_data="dividend_yield_data" type="bar"
            description="The dividend yield is the annual dividend per share divided by the stock price. A good dividend yield can be attractive to long-term investors seeking income.">
        </StockChart>
        <StockChart :chart_data="book_value_per_share_data" type="bar"
            description="This represents the company's equity on a per-share basis. It's the net asset value of the company and can be compared to the stock price to assess if the stock is undervalued or overvalued.">
        </StockChart>
        <StockChart :chart_data="price_to_earnings_ratio_data" type="bar"
            description="The P/E ratio compares the stock price to the company's earnings per share. It can help you understand if the stock is relatively expensive or cheap compared to its earnings potential.">
        </StockChart>
    </div>
</template>
